# GET https://factoriaf5.org/aprende/
# ## GET 

# POST https://jsonplaceholder.typicode.com/posts
# Content-Type: application/json

# {
#     "title": "foo",
#     "body": "bar",
#     "userId": 1
# }

# PUT  https://jsonplaceholder.typicode.com/posts/1
# Content-Type: application/json

# {
#     "title": "foo",
#     "body": "bar",
#     "userId": 1
# }

# PATCH https://jsonplaceholder.typicode.com/posts/1
# Content-Type: application/json

# {
#     "body": "Nuevo contenido del body"
# }

DELETE  https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json
